name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  NUGET_REPOSITORY_ID: GitHubPackages
  VCPKG_BINARY_SOURCES: clear;nuget,GitHubPackages,readwrite;nugettimeout,3600
  VCPKG_NUGET_REPOSITORY: https://github.com/SchaichAlonso/vcpkg.git

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup NuGet
      shell: pwsh
      run: |
        nuget sources add -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -storepasswordincleartext -name "${env:NUGET_REPOSITORY_ID}" -username "${{ github.repository_owner }}" -password "${{ secrets.NUGET_TOKEN }}"
        nuget setapikey "${{ secrets.NUGET_TOKEN }}" -source "${env:NUGET_REPOSITORY_ID}"
        nuget sources

    - name: Build
      shell: pwsh
      run: ./build.ps1
      
    - name: Run Tests
      shell: pwsh
      run: pwsh ./test.ps1
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Test Results (windows-2022)
        path: |
          build/result.xml
      
  publish-teshresults:
    name: Publish Test Results
    needs: build
    if: >
      always() &&
      github.event.sender.login != 'dependabot[bot]' &&
      ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository )
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            artifacts/**/*.xml
